package edu.ncsu.csc.itrust.unit.dao.patient;

import junit.framework.TestCase;
import edu.ncsu.csc.itrust.beans.PatientBean;
import edu.ncsu.csc.itrust.dao.mysql.PatientDAO;
import edu.ncsu.csc.itrust.exception.DBException;
import edu.ncsu.csc.itrust.unit.testutils.EvilDAOFactory;

public class PatientDAOExceptionTest extends TestCase {
	private PatientDAO evilDAO = EvilDAOFactory.getEvilInstance().getPatientDAO();

	@Override
	protected void setUp() throws Exception {
	}

	public void testAddEmptyPatientException() throws Exception {
		try {
			evilDAO.addEmptyPatient();
			fail("DBException should have been thrown");
		} catch (DBException e) {
			assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
		}
	}

	public void testDeclareHCPException() throws Exception {
		try {
			evilDAO.declareHCP(0L, 0L);
			fail("DBException should have been thrown");
		} catch (DBException e) {
			assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
		}
	}

	public void testEditPatientException() throws Exception {
		try {
			evilDAO.editPatient(new PatientBean(), 9000000003L);
			fail("DBException should have been thrown");
		} catch (DBException e) {
			assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
		}
	}
}
